language: rust
sudo: true
before_install:
- rvm install 2.5.1 && rvm use 2.5.1
- nvm install 8.12 && nvm use 8.12
- |
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  sudo apt-get update
- sudo apt-get install ghc='8.4.*' mono-devel='5.14.*' python3='3.7.*'
- bundle install
- clang --version
- ruby --version
- python3 --version
- ghc --version
- node --version
- mono --version
# Need newer compiler for some node modules
- export CC=clang CXX=clang++
script:
- make -C examples
- cd site && jekyll build --destination ../built-site --config _config.yml,_config.prod.yml; cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: built-site
  on:
    branch: master
