language: rust
sudo: false
addons:
  apt:
    sources:
      - mono
      - mono-libtiff-compat
    packages:
      - ghc
      - mono-devel
      - python3
before_install:
- rvm install 2.4.1 && rvm use 2.4.1
- nvm install 6.3 && nvm use 6.3
- bundle install
- clang --version
- ruby --version
- python3 --version
- ghc --version
- node --version
- mono --version
# Need newer compiler for some node modules
- export CC=clang CXX=clang++
script:
- make -C examples
- cd site && jekyll build --destination ../built-site --config _config.yml,_config.prod.yml; cd ..
after_success: "./deploy_gh_pages.sh"
env:
  global:
    secure: tQbG88b4WOHHQ1VK58Ah4I/XYEW0AiFcmcnVvARizSLlJk6bVx0S9neNvEi9PxTihSfidsC6TGK+gGRpsPuIJjKXs7koKMLtS0DoHjhpU72RX+QXIgvu2Yr01ZsMqpGOPhdnN4raWqDQXUqRLTJ/7xMgA81O+rkeYzZlKF21Z536IoEHT65PkxJdBh9kEP7VsAcXwBO4lGfJxLm2sBJaRf07OvlwxBNF5kSr4T0y+oYRes658cxAhiRXl316WBlFSNm4g4lSB9bewlXDYEL1Z+r0abhJIyQxN+2xvrDW9zdjGXBRX8pjTfALTHpx3hmlk24EoLQaiPQyNC3p1bvNnpglLSgy2WEFtrzQR05okyNoNn0BaemZHvCKjWsi4btYjmOKXzSZ8OMqyHAl1WNxwv5NLixJI38h8N+M1sqRX64WwZZx0gCWAKjMkh3Kaa4CNMvkP4M+4y2IalxnwAaDtZbQLkthAP4xr+rnsXOEwPcxKUBMdUuMuIYdH5QjC2kj3jOMTq2UjcpvrOA+2JSAvsYDOlj0fUrjA2YaHb35yacyNnGA/FjQ79PRtkR0FGzYISTuRJBX6CIVu99WF0yjFh3iKZOTxngbkrRqdf+DuCu/IBmSoGfHmDCfSKOxCovdpJD9kvuWpBf92nlnY+B4UZXeDneOO6Jg+05eB312NXo=
