language: minimal
sudo: required
services:
  - docker
script:
  - docker pull shepmaster/omnibus || true
  - docker build . -t shepmaster/omnibus --cache-from shepmaster/omnibus
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push shepmaster/omnibus
  - >
    docker run
    -it
    --rm
    -v $PWD/cargo:/root/.cargo/registry
    shepmaster/omnibus
    make -C /omnibus/examples
  - >
    docker run
    -it
    --rm
    -v $PWD/built-site:/built-site
    shepmaster/omnibus
    bash -c 'cd /omnibus/site && bundle && jekyll build --destination /built-site --config _config.yml,_config.prod.yml'
#- make -C /omnibus/examples
#- cd site && jekyll build --destination ../built-site --config _config.yml,_config.prod.yml; cd ..
cache:
  directories:
    - $HOME/cargo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: built-site
  on:
    branch: master
